name: "[Dispatch] Release"

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'enter version(x.y.z)'
        required: true
        default: '1.0.0'
      container_arch:
        type: choice
        description: 'choose container architecture'
        default: linux/amd64
        options:
          - "linux/amd64"
          - "linux/arm64"


env:
  VERSION: ${{ github.event.inputs.version }}
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  ARCH: ${{ github.event.inputs.container_arch }}
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  owner_check:
    if: github.repository_owner == 'forest-extension'
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.repository_owner }}
  condition_check:
    if: github.repository_owner == 'forest-extension'
    runs-on: ubuntu-latest
    needs: owner_check
    steps:
      - name: check version format
        run: |
          if [[ !(${{ env.VERSION }} =~ ^[0-9]\.[0-9]?[0-9]\.[0-9]?[0-9]$) ]];
          then
            echo "You entered an incorrect version format."
            exit 1
          fi
      - name: debugging
        run: |
          echo "major=$(echo ${{env.VERSION}} | cut -c 2- | cut -d'.' -f1)"
          echo "minor=$(echo ${{env.VERSION}} | cut -c 2- | cut -d'.' -f2)"
          echo "patch=$(echo ${{env.VERSION}} | cut -c 2- | cut -d'.' -f3)"
      - name: notice when job fails
        if: failure()
        uses: 8398a7/action-slack@v3.2.0
        with:
          status: ${{job.status}}
          fields: repo,workflow,job
          author_name: Github Action Slack

  update_master_branch_version_file:
    needs: condition_check
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT_TOKEN }}
      - name: update version file # That is used where the master_push actions
        run: |
          echo ${{ env.VERSION }} > src/VERSION
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "[CI/CD] release version ${{ env.VERSION }}"

      - name: push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PAT_TOKEN }}
          branch: master

  tagging:
    needs: update_master_branch_version_file
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT_TOKEN }}
      - name: git tagging
        run: |
          git tag ${{ env.VERSION }}
          git push origin "${{ env.VERSION }}"
      - name: notice when job fails
        if: failure()
        uses: 8398a7/action-slack@v3.2.0
        with:
          status: ${{job.status}}
          fields: repo,workflow,job
          author_name: Github Action Slack

  docker:
    needs: tagging
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT_TOKEN }}

      - name: get service name
        run: |
          echo "SERVICE=$(echo ${{ github.repository }} | cut -d '/' -f2)" >> $GITHUB_ENV

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.PAT_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: ${{ env.ARCH }}
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.repository }}:${{ env.VERSION }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Notice when job fails
        if: failure()
        uses: 8398a7/action-slack@v3.2.0
        with:
          status: ${{ job.status }}
          fields: repo,workflow,job
          author_name: Github Action Slack

#  notification:
#    needs: docker
#    runs-on: ubuntu-latest
#    steps:
#      - name: Slack
#        if: always()
#        uses: 8398a7/action-slack@v3.2.0
#        with:
#          status: ${{job.status}}
#          fields: repo,message,commit,author,action,ref,workflow,job
#          author_name: Github Action Slack
